### PR TITLE
fix jspsych-percent-sum.js field font-size and parsing

### PR DESCRIPTION
**Pull request by Floozutter**
Addresses #16 and #18.

This became kind of a mess because I didn't realize that [HTML number inputs containing invalid numbers have their values set to the empty string](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)). Basically, `parseField` was passing tests on bad arguments, but it didn't behave the same way in the trial because there `parseField` was just getting `""` instead.

### CODE REVIEW

**Comment by Floozutter** [comment]
Oof.

**Review by noah10 — COMMENTED** [review]
I think this is OK, with a couple of caveats:

- I'm not sure what rules we're trying to follow for the number parsing. For example, 001 will be converted to 1, which seems fine to me, but then converting 1.1 to 1 also seems fine to me.
- This should have been two pull requests: One for the font size and one for the number parsing.

If the 001 -> 1 thing is OK then I'll go ahead and merge this in.

**Comment by Floozutter** [comment]
- The rule I was trying to follow was: valid non-negative integers only, no truncation or rounding allowed.
- Ah, right, sorry. I was reminded of how non-strict the parsing was while testing the font-size, and started committing work to the `issue-16` branch.

At the moment, this line's test allows leading zeros:
https://github.com/EmotionCognitionLab/pvs/blob/126dd20e4cde45ca58a50de840d0258092c9db0e/baseline/client/tests/jspsych-percent-sum.test.js#L110
And this line's test disallows decimal numerals:
https://github.com/EmotionCognitionLab/pvs/blob/126dd20e4cde45ca58a50de840d0258092c9db0e/baseline/client/tests/jspsych-percent-sum.test.js#L119

(The current implementation passes all tests.)

Do you think I should make any changes?

**Comment by noah10** [comment]
Ah - I missed the '08' test. And no, as long as that's something we want it's fine by me. I'll go ahead and merge this.

**Review by noah10 — APPROVED** [review]

**Pull request merged**
